### ISSUE TITLE
Apache httpd

### ISSUE THREAD

**Issue by corvus-ch** [Docker-nano/template#1]
I have started working on a apache http container based on Docker-nano. I still have trouble compiling http but I have put the most basic parts together. See https://github.com/corvus-ch/docker-nano-httpd.

I really like the idea of having really small docker containers at hand and I would be honored if my contribution to that idea will end up unter the docker-nano namespace. Given I can figure out that compiling issue – help would be appreciated.

**Comment by Bilge** [comment]
I'm thrilled that you wish to be the first contributor to the project! I'll do what I can to help you get your product working. If you like, we can discuss any issues on #nano (Freenode). In the meantime I'll check out your project and see if I can replicate the issue you're having.

Can you share the errors you're experiencing? If they're related to Buildroot you may find the guys at #buildroot more helpful than myself.

**Comment by corvus-ch** [comment]
Sure thing. See https://github.com/corvus-ch/docker-nano-httpd/issues/1. I have linked a gist there containing the log output.

**Comment by Bilge** [comment]
Take a look at http://patchwork.ozlabs.org/patch/396684/. It has a patch for the gen_test_char problem.

**Comment by corvus-ch** [comment]
Thanks that helped a lot. What's left now is to have the apache configured to actually deliver stuff.

**Comment by Bilge** [comment]
That probably should be left to consumers of the image, but providing a template might be useful for some people to get started.

**Comment by corvus-ch** [comment]
So, I clean stuff up a little bit. I am now quite satisfied with the result. What now is left is setting up travis and have the result published to the docker registry. How shall we proceed here.

@Bilge: Are you providing me access to the docker-nano and nano namespaces or will you take care of that task?

**Comment by Bilge** [comment]
I will add you to the organization so you have direct push access.

**Comment by Bilge** [comment]
You should now have an invitation to join the team. When you accept you will have push access to [Apache](https://github.com/Docker-nano/Apache). You will need an encrypted `.git-credentials` file to automate [Travis-bot](https://github.com/Travis-bot) which I will add when you've done the first push!

**Comment by corvus-ch** [comment]
Repository pushed. Thanks for the support.
